version: '3.9'

services:
  backend:
    build: ./backend
    ports:
      - "5328:5328"
    environment:
      - FLASK_APP=api/app.py
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - TAVILY_API_KEY=${TAVILY_API_KEY}
      - LLAMA_CLOUD_API_KEY=${LLAMA_CLOUD_API_KEY}
    volumes:
      - ./backend:/app

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_BASE_URL=http://backend:5328
    #volumes:
    #  - ./frontend:/app
    depends_on:
      - backend
